# Module to facilitate directory syncing between hosts using unison.
#
# Bidirectional by default. Unison reconciles both sides rather than mirroring
# one onto the other, which is the point of using it over rsync.
# --push and --pull exist for when one side is known good.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.nixSpace.programs.hostSync;

  localPlatform = if pkgs.stdenv.hostPlatform.isDarwin then "darwin" else "linux";

  hostType = lib.types.submodule (
    { name, ... }:
    {
      options = {
        target = lib.mkOption {
          type = lib.types.str;
          default = name;
          defaultText = lib.literalMD "The attribute name.";
          description = ''
            ssh destination, if it differs from the attribute name.

            For a host reachable at a different address than the name you
            want to type: `sync macmini` vs. `user@10.0.1.4`.
          '';
        };

        platform = lib.mkOption {
          type = lib.types.enum [
            "linux"
            "darwin"
          ];
          default = if pkgs.stdenv.hostPlatform.isDarwin then "darwin" else "linux";
          defaultText = lib.literalMD "This machine's platform.";
          description = ''
            The remote host's platform.

            Determines whether permissions are propagated: two hosts of the
            same platform will sync permissions.        

            The default assumes	the remote matches this machine.
          '';
        };

        paths = lib.mkOption {
          type = lib.types.nullOr (lib.types.listOf lib.types.str);
          default = null;
          description = ''
            Paths to sync with this host, relative to the home directory, or
            null to use the module-level `paths`.
          '';
        };

        excludePaths = lib.mkOption {
          type = lib.types.nullOr (lib.types.listOf lib.types.str);
          default = null;
          description = ''
            Paths NOT to sync with this host, or null for the module-level
            `excludePaths`.
          '';
        };
      };
    }
  );

  hostPaths = host: if host.paths == null then cfg.paths else host.paths;
  hostExcludes = host: if host.excludePaths == null then cfg.excludePaths else host.excludePaths;

  mkProfile = name: host: ''
    # Generated by nixSpace.programs.hostSync for ${name}. 
    # Edits are overwritten on the next activation.
    #
    # Root order matters: root 1 is local and root 2 is remote, which is what
    # the -nocreation=N arguments in host-sync refer to.
    root = ${config.home.homeDirectory}
    root = ssh://${host.target}/${config.home.homeDirectory}

    ${lib.concatMapStringsSep "\n" (p: "path = ${p}") (hostPaths host)}

    ${lib.concatMapStringsSep "\n" (p: "ignore = ${p}") cfg.excludePatterns}
    ${lib.concatMapStringsSep "\n" (p: "ignore = Path ${p}") (hostExcludes host)}

    # The remote unison must be the SAME majore version as the local one:
    # unison refuses to talk to a mismatched peer. A store path pins the local
    # side; the remote resolves this path in its own store, which works
    # because both hosts run the same nixpkgs.
    servercmd = ${pkgs.unison}/bin/unison

    auto = ${if cfg.autoAcceptUnchanged then "true" else "false"}
    times = true

    # Permissions propagate only between hosts of the SAME platform.
    #
    # perms is a bitmask of the mode bits unison will sync; 0 means none.
    # Linux and macOS disagree about what modes mean. 
    #
    # 0o1777 covers the permission bits plus setuid, setgid, and sticky,
    # which is unison's default for same-platform pairs.
    perms = ${if host.platform == localPlatform then "0o1777" else "0"}
  '';

  # This host removed, so a fleet can share one list.
  activeHosts =
    if cfg.localHost == null then
      cfg.hosts
    else
      lib.filterAttrs (name: _h: name != cfg.localHost) cfg.hosts;

  syncScript = pkgs.writeShellApplication {
    name = "host-sync";
    runtimeInputs = [
      pkgs.unison
      pkgs.openssh
    ];

    text = ''
      KNOWN_HOSTS="${lib.concatStringsSep " " (lib.attrNames activeHosts)}"
      SSH_TIMEOUT="${toString cfg.sshTimeout}"
      CHECK_REACHABLE="${if cfg.checkReachable then "1" else "0"}"
    ''
    + builtins.readFile ./host-sync.sh;
  };
in
{
  options.nixSpace.programs.hostSync = {
    enable = lib.mkEnableOption "home directory sync between hosts";

    hosts = lib.mkOption {
      type = lib.types.attrsOf hostType;
      default = { };
      example = lib.literalExpression ''
        {
          host1 = { };
          host2 = { };
          host1.excludePaths = [ "Projects/work-only" ];
        }
      '';
      description = ''
        Hosts to sync with, keyed by name.

        An empty attrset per host is the normal case. It inherits the
        module-level paths and excludes, and the name is the ssh destination.

        With mixed hosts, set `platform` per host. It defaults to this
        machine's, which is right for a Linux-only or Darwin-only group.
      '';
    };

    localHost = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      example = "framework16";
      description = ''
        This machine's name, removed from `hosts` if present.

        So a fleet can share ONE host list rather than each machine carrying a
        list of the others — which is four nearly-identical blocks for four
        hosts, and a new host means editing every one.

        home-manager does not know the hostname, so this has to be told.
      '';
    };

    paths = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      example = [
        "Documents"
        "Projects"
      ];
      description = ''
        Paths to sync, relative to the home directory, for hosts that do not
        override them.

        Unison syncs only what is listed.
      '';
    };

    excludePaths = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      example = [ "Downloads/Work" ];
      description = ''
        Exact paths to exclude, for hosts that do not override them.
      '';
    };

    excludePatterns = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "Name .git"
        "Name node_modules"
        "Name .DS_Store"
        "Name Thumbs.db"
        "Path .cache"
        "Path .local/share/Trash"
      ];
      description = ''
        Unison ignore rules applied to every host.

        Unison's own syntax, and the prefix matters: `Name x` matches that
        name ANYWHERE in the tree, `Path x` matches one path from the root,
        `Regex` takes a pattern.

        .git is excluded by default because syncing a repository's object
        store between machines that both have it checked out invites
        corruption: push and pull instead.
      '';
    };

    autoAcceptUnchanged = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Accept unison's recommendation for non-conflicting changes.

        Conflicts still prompt. This only skips confirmation where one side
        changed and the other did not.

        False makes every sync interactive.
      '';
    };

    sshTimeout = lib.mkOption {
      type = lib.types.ints.positive;
      default = 5;
      description = ''
        Seconds to wait when checking a host is reachable.

        The check is `ssh -o BatchMode=yes <host> true`, which tests
        authentication as well as reachability. A port check passes on a
        host whose sshd rejects your key, but unison will fail with the
        error buried in its output.
      '';
    };

    checkReachable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Probe the host with ssh before starting unison.

        Off by default because it interacts badly with keys that need a
        passphrase or a hardware touch: the probe runs with BatchMode=yes,
        which disables prompts, so a perfectly reachable host fails the check.

        Enable only where authentication is non-interactive: an agent already 
        holding the key, or a key with no passphrase.
      '';
    };

  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.paths != [ ] || lib.all (h: h.paths != null) (lib.attrValues cfg.hosts);
        message = ''
          nixSpace.programs.hostSync has no paths: both the module-level
          `paths` and per-host overrides are missing.
        '';
      }
    ];

    home = {
      packages = [
        pkgs.unison
        syncScript
      ];

      sessionVariables = {
        NS_SYNC_HOSTS = lib.concatStringsSep " " (lib.attrNames activeHosts);
        NS_SYNC_SSH_TIMEOUT = toString cfg.sshTimeout;
      };

      file = lib.mapAttrs' (
        name: host: lib.nameValuePair ".unison/${name}.prf" { text = mkProfile name host; }
      ) activeHosts;
    };
  };
}
