# Hyprland preset.
#
# A PRESET, not a wrapper. It sets defaults on home-manager's own
# wayland.windowManager.hyprland options rather than re-exposing them under a
# nixSpace namespace. Everything here uses lib.mkDefault, so a consumer who
# wants different gaps writes:
#
#   wayland.windowManager.hyprland.settings.config.general.gaps_in = 8;
#
# directly, with no option in this module to go through. Mirroring hundreds of
# Hyprland settings behind nixSpace.* equivalents would double the surface for
# no gain — the upstream options already exist and are already documented.
#
# What DOES get an option: things the module cannot know (monitors) and things
# where a wrong default is a hardware fact rather than a taste (nvidia).
#
# LUA ONLY. hyprlang is deprecated as of 0.55 and the settings below use the
# Lua shapes — hl.config sections, hl.curve for beziers, typed monitor and
# window_rule tables. Under configType = "hyprlang" these would render as
# nonsense, so the assertion below rejects that combination rather than
# producing a config that fails at compositor startup.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.nixSpace.hyprland;
  inherit (lib.generators) mkLuaInline;
in
{
  # ./desktop is NOT imported here, deliberately.
  #
  # `hyprland` is a compositor; `hyprdesktop` is an assembled environment
  # built on it. Importing the bundle from the compositor preset would reduce
  # that boundary to an enable default — and the failure mode is worse than it
  # sounds: someone running bare Hyprland who sets a hyprdesktop option would
  # get no error, because the option exists and is merely inert. Leaving it
  # unimported produces "option does not exist", which names the problem.
  #
  # The register imports it under the hyprdesktop tag. Testing without the
  # register means importing both paths by hand, which also makes the
  # dependency visible rather than transitive.

  options.nixSpace.hyprland = {
    enable = lib.mkEnableOption "Hyprland with wlr-which-key integration";

    monitors = lib.mkOption {
      type = lib.types.listOf (lib.types.attrsOf lib.types.anything);
      default = [ ];
      example = lib.literalExpression ''
        [
          { output = "HDMI-A-2"; mode = "preferred"; position = "0x0"; scale = 1; }
          { output = ""; mode = "preferred"; position = "auto"; scale = 1; mirror = "HDMI-A-2"; }
        ]
      '';
      description = ''
        Monitor layout, one table per output. An OPTION rather than a default
        because it is per-machine — there is no sensible fleet-wide value, and
        a wrong one leaves a laptop with no display.

        Passed through to hl.monitor() verbatim; see the monitor spec in
        <hyprland>/share/hypr/stubs/hl.meta.lua for valid fields. An entry with
        output = "" is the catch-all applied to any output not matched above.

        Empty means no explicit layout: Hyprland auto-detects, which is usually
        right for a single-display machine.
      '';
    };

    windowRules = lib.mkOption {
      type = lib.types.listOf (lib.types.attrsOf lib.types.anything);
      default = [ ];
      example = lib.literalExpression ''
        [
          {
            name = "firefox-pip";
            match.title = "^(Picture-in-Picture)$";
            float = true;
            pin = true;
            size = "30% 30%";
            move = "65% 5%";
          }
        ]
      '';
      description = ''
        Window rules, passed to hl.window_rule() verbatim.

        No defaults: a rule names an application class or title, which only
        exists on a machine running that application. Shipping rules for
        Steam or Firefox would be guessing at what is installed.

        Feature modules in the hyprdesktop bundle contribute their own rules
        here — listOf concatenates, so adding to this list does not displace
        them.

        CAUTION: unknown fields in a rule are NOT rejected by
        `Hyprland --verify-config` the way unknown hl.config keys are. A
        misspelled effect parses cleanly and does nothing. Check names against
        HL.WindowRuleSpec in <hyprland>/share/hypr/stubs/hl.meta.lua.
      '';
    };

    workspaceRules = lib.mkOption {
      type = lib.types.listOf (lib.types.attrsOf lib.types.anything);
      default = [ ];
      example = lib.literalExpression ''
        [
          {
            workspace = "2";
            monitor = "DP-2";
            default = true;
          }
        ]
      '';
      description = ''
        Workspace rules, passed to hl.workspace_rule() verbatim.

        `workspace` is the required field and names the workspace the rule
        applies to: see HL.WorkspaceRuleSpec in
        <hyprland>/share/hypr/stubs/hl.meta.lua for the rest.

        The scratchpad rule generated by scratchpadLayout is prepended to
        this list, so a rule here can add to it without displacing it.

        CAUTION: an unknown field is silently ignored rather than rejected.
        The scratchpad rule was written with `match` for a while, a field
        that does not exist on this spec, and the layout simply never
        applied, with a clean verify-config run.
      '';
    };

    mainMod = lib.mkOption {
      type = lib.types.str;
      default = "SUPER";
      description = ''
        Primary modifier. Emitted as a Lua local, so every bind referencing it
        changes with this value rather than needing individual edits.
      '';
    };

    shiftMod = lib.mkOption {
      type = lib.types.str;
      default = "SHIFT";
      description = "Secondary modifier, combined with mainMod.";
    };

    altMod = lib.mkOption {
      type = lib.types.str;
      default = "ALT";
      description = ''
        Tertiary modifier, used for layout navigation so those binds do not
        collide with the mainMod directional set.

        CAUTION: ALT is heavily used by applications — Alt+key in terminals,
        GTK menu accelerators. A Hyprland bind wins, so those stop reaching the
        application.
      '';
    };

    terminal = lib.mkOption {
      type = lib.types.str;
      default = config.nixSpace.programs.terminals.primaryCommand;
      description = "Terminal command, bound to mainMod + Q.";
    };

    launcher = lib.mkOption {
      type = lib.types.str;
      default = config.nixSpace.programs.launchers.primaryCommand;
      description = "Application launcher command, bound to mainMod + R.";
    };

    nvidia = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Apply NVIDIA-specific session variables.

        A hardware fact, not a preference, which is why it is an option rather
        than a default. WLR_NO_HARDWARE_CURSORS works around cursor corruption
        on NVIDIA; setting it on AMD or Intel forces software cursors for no
        reason.

        Set from the hw-nvidia-dgpu tag in the register, not declared per host.
      '';
    };

    startupCommands = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      example = [ "hypr-session-restore" ];
      description = ''
        Extra commands run on hyprland.start, after the preset's own.

        There is no exec-once under Lua: the attribute name would render as
        hl.exec-once(...), and a hyphen in a Lua identifier is subtraction.
        Startup commands go in an hl.on("hyprland.start", ...) hook, which can
        be registered more than once — so this is additive rather than
        replacing home-manager's own systemd-environment hook.
      '';
    };

    clipboardHistory = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Run cliphist watchers for text and image clipboard history.";
    };

    polkitAgent = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Start hyprpolkitagent at session start.

        Without an authentication agent, anything that prompts for privilege
        fails silently — no dialog, no error, the action simply does not
        happen.
      '';
    };

    scratchpadName = lib.mkOption {
      type = lib.types.str;
      default = "magic";
      description = ''
        Name of the special workspace used as a scratchpad.

        Read by both the workspace rule below and the which-key toggle entry,
        so the two cannot disagree — they are the same workspace, and a
        mismatch gives a rule applying to one and a bind toggling another.
      '';
    };

    scratchpadLayout = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = "scrolling";
      example = "dwindle";
      description = ''
        Layout for the scratchpad workspace, or null to inherit
        general.layout.

        Scrolling suits a scratchpad: windows land on a horizontal tape you
        page through, rather than subdividing a fixed area as dwindle does —
        so a fourth window does not shrink the other three.

        Built in since Hyprland 0.56; earlier versions needed a plugin.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # The home-manager service, not an exec_cmd in the startup hook.
    #
    # The hook fires before the session environment is fully imported, which
    # is the same race that had waybar dying on a portal activation timeout.
    # A unit gets proper ordering against graphical-session.target instead.
    services.hyprpolkitagent.enable = cfg.polkitAgent;

    wayland.windowManager.hyprland = {
      enable = true;

      # hyprlang is deprecated and this module does not support it
      configType = lib.mkForce "lua";

      # The system provides the compositor (programs.hyprland.enable), which
      # also installs the session entry and the portal. Installing it here too
      # puts two builds in the closure and leaves which one runs to PATH order.
      package = lib.mkDefault null;
      portalPackage = lib.mkDefault null;

      settings = {

        # Modifier locals. Emitted as `local mainMod = "SUPER"` — the $-prefixed
        # hyprlang form is not a legal Lua identifier.
        mainMod._var = cfg.mainMod;
        shiftMod._var = cfg.shiftMod;
        altMod._var = cfg.altMod;

        config = {
          general = {
            gaps_in = lib.mkDefault 4;
            gaps_out = lib.mkDefault 10;
            border_size = lib.mkDefault 2;

            # Gradient borders are a table, not the hyprlang
            # "rgba(a) rgba(b) 45deg" string.
            col = {
              active_border = lib.mkDefault {
                colors = [
                  "rgba(7ebae4ee)"
                  "rgba(5277c3ee)"
                ];
                angle = 45;
              };
              inactive_border = lib.mkDefault "rgba(595959aa)";
            };

            layout = lib.mkDefault "dwindle";
            allow_tearing = lib.mkDefault false;
          };

          decoration = {
            rounding = lib.mkDefault 10;
            blur = {
              enabled = lib.mkDefault true;
              size = lib.mkDefault 3;
              passes = lib.mkDefault 1;
            };
            shadow = {
              enabled = lib.mkDefault true;
              range = lib.mkDefault 4;
              render_power = lib.mkDefault 3;
              color = lib.mkDefault "rgba(1a1a1aee)";
            };
          };

          input = {
            kb_layout = lib.mkDefault "us";
            repeat_rate = lib.mkDefault 50;
            repeat_delay = lib.mkDefault 300;

            # 0 = cursor does not change focus
            # 1 = focus always follows the cursor
            # 2 = cursor focus detached from keyboard focus; clicking switches
            # 3 = fully separate; clicking does not switch keyboard focus
            follow_mouse = lib.mkDefault 2;

            sensitivity = lib.mkDefault 1.0;
            touchpad = {
              natural_scroll = lib.mkDefault true;
              scroll_factor = lib.mkDefault 0.7;
              clickfinger_behavior = lib.mkDefault true; # 1=LMB 2=RMB 3=MMB
              disable_while_typing = lib.mkDefault true;
            };
          };

          # Only the enable flag. Individual animations are separate
          # hl.animation() calls and beziers are hl.curve().
          animations.enabled = lib.mkDefault true;

          # dwindle.pseudotile was removed in 0.53 — pseudotiling is toggled
          # by the pseudo dispatcher only.
          dwindle.preserve_split = lib.mkDefault true;

          master.new_status = lib.mkDefault "master";

          misc.force_default_wallpaper = lib.mkDefault 0;

          xwayland.force_zero_scaling = lib.mkDefault true;

          # Enfornce the Wayland permission system.
          ecosystem.enforce_permissions = lib.mkDefault true;
          # Preserve logs by default.
          debug.disable_logs = lib.mkDefault false;
        }
        // lib.optionalAttrs (cfg.scratchpadLayout == "scrolling") {
          # Conditionally configure scrolling layout
          # Fit method 0 = center, 1 = fit
          scrolling = {
            focus_fit_method = lib.mkDefault 0;
            fullscreen_on_one_column = lib.mkDefault true;
          };
        };

        curve = {
          _args = [
            "myBezier"
            {
              type = "bezier";
              points = [
                [
                  0.05
                  0.9
                ]
                [
                  0.1
                  1.05
                ]
              ];
            }
          ];
        };

        animation = lib.mkDefault (
          map (a: { _args = [ a ]; }) [
            {
              leaf = "windows";
              enabled = true;
              speed = 4;
              bezier = "myBezier";
            }
            {
              leaf = "windowsOut";
              enabled = true;
              speed = 4;
              bezier = "default";
              style = "popin 80%";
            }
            {
              leaf = "border";
              enabled = true;
              speed = 5;
              bezier = "default";
            }
            {
              leaf = "borderangle";
              enabled = true;
              speed = 6;
              bezier = "default";
            }
            {
              leaf = "fade";
              enabled = true;
              speed = 4;
              bezier = "default";
            }
            {
              leaf = "workspaces";
              enabled = true;
              speed = 4;
              bezier = "default";
            }
          ]
        );

        # hl.env takes two arguments. The hyprlang "NAME,value" single string
        # would render as one argument and be silently wrong.
        env = [
          {
            _args = [
              "XCURSOR_SIZE"
              "24"
            ];
          }
        ]
        ++ lib.optional cfg.nvidia {
          _args = [
            "WLR_NO_HARDWARE_CURSORS"
            "1"
          ];
        };

        gesture = lib.mkDefault {
          _args = [
            {
              fingers = 3;
              direction = "horizontal";
              action = "workspace";
            }
          ];
        };

        monitor = map (m: { _args = [ m ]; }) cfg.monitors;

        # Mouse binds. movewindow/resizewindow became window.drag/window.resize.
        bind = [
          {
            _args = [
              (mkLuaInline ''mainMod .. " + mouse:272"'')
              (mkLuaInline "hl.dsp.window.drag()")
            ];
          }
          {
            _args = [
              (mkLuaInline ''mainMod .. " + mouse:273"'')
              (mkLuaInline "hl.dsp.window.resize()")
            ];
          }
        ];

        # One hl.workspace_rule() call per entry. The scratchpad rule comes
        # first so an explicit rule for the same workspace can override it
        # later calls win.
        workspace_rule = map (rule: { _args = [ rule ]; }) (
          lib.optional (cfg.scratchpadLayout != null) {
            workspace = "special:${cfg.scratchpadName}";
            layout = cfg.scratchpadLayout;
          }
          ++ cfg.workspaceRules
        );

        window_rule = cfg.windowRules;

        on = {
          _args = [
            "hyprland.start"
            (mkLuaInline ''
              function()
              ${lib.concatMapStringsSep "\n" (c: ''hl.exec_cmd("${c}")'') (
                lib.optionals cfg.clipboardHistory [
                  "wl-paste --type text --watch cliphist store"
                  "wl-paste --type image --watch cliphist store"
                ]
                ++ cfg.startupCommands
              )}
              end
            '')
          ];
        };
      };
    };

    home.packages = lib.optional cfg.clipboardHistory pkgs.cliphist ++ [
      pkgs.wl-clipboard
      pkgs.hyprshot
    ];
  };
}
