{ pkgs, ... }:
let
  uhdPackage = pkgs.uhd;
  # Store the udev rules generated by the uhd package to dynamically populate extra rules
  udevRulesPath = "${uhdPackage}/lib/udev/rules.d/uhd-usrp.rules";
in
{
  environment.systemPackages = with pkgs; [
    uhd # Include UHD in system packages
  ];

  # Dynamically set additional udev rules
  services.udev.extraRules = builtins.readFile udevRulesPath;
}
